SELECT
    ADDRESSES.ROWID as ID,
    ADDRESSES.Address || ' ' || ADDRESSES.Post_Code || ', ' || ADDRESSES.Country as TXT,
    ADDRESSES.USE as USE
FROM PATIENTS
JOIN ADDRESSES ON ADDRESSES.PATIENT_ID=PATIENTS.ROWID
WHERE PATIENTS.ROWID = ?
ORDER BY Use DESC