SELECT
REFERRING_DOCTORS.DOCTOR_ID as ID,
DOCTORS.Title || ' ' || DOCTORS.First_Name || ' ' || Doctors.Second_Name || ' (' || DOCTORS.Job_Title || ') ' as TXT,
REFERRING_DOCTORS.USE as USE
FROM Patients
JOIN REFERRING_DOCTORS ON Patients.ROWID=REFERRING_DOCTORS.PATIENT_ID
JOIN DOCTORS ON REFERRING_DOCTORS.DOCTOR_ID=DOCTORS.ROWID
WHERE Patients.ROWID=?
ORDER BY Use DESC, DOCTORS.Second_Name ASC