SELECT
    TELEPHONES.ROWID as ID,
    TELEPHONES.Telephone as TXT,
    TELEPHONES.USE as USE
FROM PATIENTS
JOIN TELEPHONES ON TELEPHONES.PATIENT_ID=PATIENTS.ROWID
WHERE PATIENTS.ROWID = ?
ORDER BY USE DESC
