SELECT
    ADDRESSES.ROWID as ID,
    ADDRESSES.Address || ' ' || ADDRESSES.POST_CODE || ', ' || ADDRESSES.COUNTRY as TXT,
    ADDRESSES.Use as USE
FROM PATIENTS
JOIN ADDRESSES ON ADDRESSES.PATIENT_ID=PATIENTS.ROWID
WHERE PATIENTS.ROWID = ? AND ADDRESSES.USE=1
ORDER BY Use DESC