SELECT
    PATIENTS.ROWID,
    ADDRESSES.Address || ' ' || ADDRESSES.POST_CODE || ', ' || ADDRESSES.COUNTRY as Address,
    ADDRESSES.Use
FROM PATIENTS
JOIN ADDRESSES ON ADDRESSES.PATIENT_ID=PATIENTS.ROWID
WHERE PATIENTS.ROWID = ?
ORDER BY Use DESC