SELECT
    REFERRRING_DOCTORS.ROWID,
    DOCTORS.Title || ' ' || DOCTORS.FirstName || ' ' || DOCTORS.SecondName as Doctor
FROM REFERRRING_DOCTORS
JOIN PATIENTS ON REFERRRING_DOCTORS.PATIENT_ID=PATIENTS.ROWID
JOIN DOCTORS ON DOCTORS.ROWID=REFERRRING_DOCTORS.ROWID
WHERE PATIENTS.ROWID = ?